### ISSUE TITLE
Bowser support

### ISSUE THREAD

**Issue by nyrtZi** [simplewebrtc/SimpleWebRTC#335]
The old issue #56 about the matter was closed I'm opening a new one.

Bowser is back.
http://www.openwebrtc.org/bowser/

Quoting from the webpage:
"It is built on top of OpenWebRTC and is available for both iPhone and iPad. As part of releasing Bowser as Open Source it was also re-submitted to the Apple App Store and can be downloaded for free here."

They seem to be behind the current standards through:
https://github.com/EricssonResearch/openwebrtc/issues/492

Any chance of this getting picked up again?

**Comment by xdumaine** [comment]
Thanks for the suggestion. Specific issues or details around what is broken would help, as well as any code contributions, if you can.

**Comment by fippo** [comment]
everyone is behind on standards.
@stefanalund: does bowser work with adapter? Then it might just work...

**Comment by stefanalund** [comment]
@stefhak just made a list of what is missing from a standards perspective: https://github.com/EricssonResearch/openwebrtc/issues/492. Last week, however, we landed some pretty significant compatibility fixes such as 

https://github.com/EricssonResearch/openwebrtc/pull/427 and
https://github.com/EricssonResearch/openwebrtc/pull/486

On top of that Bowser is being moved to `WKWebView` making it substantially more robust:

https://github.com/EricssonResearch/bowser/pull/61

These things combined will hopefully make the next version (0.6) of Bowser a lot more usable. We are of course really happy to get support in terms of contributions to Bowser/OpenWebRTC :smile: 

What would be a good app to use for testing SimpleWebRTC in Bowser?

**Comment by stefanalund** [comment]
When testing on your demo app (yeah, I should have checked before asking...) I see that SimpleWebRTC does not seem to recognise that Bowser supports WebRTC:

![screen shot 2015-10-24 at 22 15 58](https://cloud.githubusercontent.com/assets/190856/10712504/fad44a06-7a9c-11e5-8add-5094fcb863ff.png)

(Checking for VP8 support through asking the `<video>` element if it supports playback of that media type is flawed. In Bowser's case, media playback and WebRTC video support are different).

**Comment by stefanalund** [comment]
Digging a bit more I found that it may actually be the VP8 thingy that tells SimpleWebRTC that Bowser does not support WebRTC: https://github.com/HenrikJoreteg/webrtcsupport/issues/9

**Comment by stefanalund** [comment]
Sent an PR: https://github.com/HenrikJoreteg/webrtcsupport/pull/20

**Comment by stefanalund** [comment]
@fippo any update on this?
